apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      containers:
      - name: argocd-application-controller
        resources:
          limits:
            cpu: 750m
            memory: 750Mi
          requests:
            cpu: 200m
            memory: 200Mi
