apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- base.yaml
#GKE (which was used for development) uses Cilium which can lead to a bug in ArgoCD: https://github.com/cilium/cilium/issues/17349
patches:
- path: argocd-application-controller.yaml
- path: argocd-applicationset-controller.yaml
- path: argocd-dex-server.yaml
- path: argocd-notifications-controller.yaml
- path: argocd-redis.yaml
- path: argocd-repo-server.yaml
- path: argocd-server.yaml
- path: argocd-cm.yaml
