apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-backend-files
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: {{.Values.backend.files.volumeSize}}
