apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: vikunja-frontend
  name: vikunja-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: vikunja-backend
  name: vikunja-backend
