apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vikunja-frontend
  name: vikunja-frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: vikunja-frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: vikunja-backend
  name: vikunja-backend
spec:
  ports:
  - name: api
    port: 3456
    protocol: TCP
    targetPort: api
  selector:
    app.kubernetes.io/name: vikunja-backend
